project:
  type: book

book:
  title: "Analyse libellenmeetnetten"
  subtitle: "Technisch rapport"
  date: "2025-11-19"
  author:
    name: "Toon Westra, Geert De Knijf, Sam Van De Poel, Hannes Ledegen, Frederic Piesschaert, Thierry Onkelinx"
    email: "Toon.Westra@inbo.be"
  chapters:
    - index.qmd
    - 1_selectie_analyseset.qmd
    - 2_dataverkenning.qmd
    - 3_analysis.qmd
format: html
editor: source
lang: nl
execute:
  cache: true
  echo: false
  warning: false